import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
  },
  header: {
    marginBottom: 20,
    borderBottom: 1,
    borderBottomColor: '#eeeeee',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  subtitle: {
    fontSize: 10,
    color: '#666666',
    marginTop: 4,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  content: {
    fontSize: 12,
    lineHeight: 1.6,
    color: '#333333',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    borderTop: 1,
    borderTopColor: '#eeeeee',
    paddingTop: 10,
    fontSize: 8,
    color: '#999999',
    textAlign: 'center',
  },
});

interface NotePDFProps {
  title: string;
  content: string;
  projectName: string;
}

export const NotePDF = ({ title, content, projectName }: NotePDFProps) => {
  // Strip HTML tags for PDF simplicity (better to use a proper HTML-to-PDF mapper in production)
  const plainText = content.replace(/<[^>]*>?/gm, '\n');

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.subtitle}>{projectName} • PROJECT WORKSPACE</Text>
        </View>
        
        <View style={styles.content}>
          <Text>{plainText}</Text>
        </View>

        <Text style={styles.footer}>
          Generated by Workspace OS Platform on {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
};
